version: 2

# Dependabot configuration for Heavens Above project
# This file configures automated dependency updates

updates:
  # Monitor GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
     
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    
  
    open-pull-requests-limit: 3
    
    assignees:
      - "Maryam1234678"  
    
    reviewers:
      - "Maryam1234678"  
    
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    
    commit-message:
      prefix: "ci"
      include: "scope"
    
    pull-request-branch-name:
      separator: "/"
    
    rebase-strategy: "auto"
    
    allow:
      - dependency-type: "all"
